using static _2024LeetCode.TwoSum_Test;
using static _2024LeetCode.PerfectSet;
using static _2024LeetCode.LongestCommonPrefix;
using static _2024LeetCode.ContainerWithMaxVolume;
using static _2024LeetCode.Atoi;
using static _2024LeetCode.ReverseInt;
using static _2024LeetCode.ZigZagConversion;
using static _2024LeetCode.LongestPalindromicSubstring;
using static _2024LeetCode.LongestSubstringWithoutRepeatCharacters;
using static _2024LeetCode.RotateMatrixNinetyDegrees;
using static _2024LeetCode.KaprekarsContant;
using static _2024LeetCode.AddTwoNumbers;
using static _2024LeetCode.PivotPartitionList;
using static _2024LeetCode.CompressString;
using static _2024LeetCode.BinaryTreeRootToLeafPaths;
using static _2024LeetCode.ThreeSum;
using static _2024LeetCode.RotateArray;

Console.WriteLine("Leet Code - 2024!");
Console.WriteLine('\n');
TwoSum_StartTest();
Console.WriteLine('\n');
TestMaxSetSize();
Console.WriteLine('\n');
TestLongestCommonPrefix();
Console.WriteLine('\n');
TestMaxArea();
Console.WriteLine('\n');
TestMyAtoi();
Console.WriteLine('\n');
TestReverse();
Console.WriteLine('\n');
TestConvert();
Console.WriteLine('\n');
TestLongestPalndrome();
Console.WriteLine('\n');
TestLengthOfLongestSubstring();
Console.WriteLine('\n');
_2024LeetCode.RotateMatrixNinetyDegrees.TestRotate();
Console.WriteLine('\n');
TestKaprekar();
Console.WriteLine('\n');
TestAdd2Numbers();
Console.WriteLine('\n');
TestPivot();
Console.WriteLine('\n');
TestCompressString();
Console.WriteLine('\n');
TestGetAllRootToLeafPaths();
Console.WriteLine('\n');
TestGetThreeSums();
Console.WriteLine('\n');
_2024LeetCode.RotateArray.TestRotate();